convenzioni-cisl-uil/ads/urls.py
from django.conf.urls import url
from .views import TraceUrl

urlpatterns = [
    url(r'^apri/(?P<pk>\d+)$', TraceUrl.as_view(), name='ads-trace-url'),
]

convenzioni-cisl-uil/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from rest_framework import routers

from .views import SuggestionsFormView, RewriteView, AgreementProposalView, news_feeds # noqa
from agreements.views import CategoryViewSet, CompanyViewSet, PointViewSet
from ads.views import BannerViewSet

# API
router = routers.DefaultRouter()
router.register(r'categorie', CategoryViewSet)
router.register(r'aziende', CompanyViewSet)
router.register(r'rivenditori', PointViewSet)
router.register(r'ads', BannerViewSet)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    # login
    url(r'^login/?$', 'django.contrib.auth.views.login'),
    url(r'^logout/?$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    # ckeditor uploader
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # treenav
    url(r'^treenav/', include('treenav.urls')),
    # ads
    url(r'^ads/', include('ads.urls')),
    # news
    url(r'^news/', include('news.urls')),
    # suggerimenti
    url(r'^suggerimenti/inviati/', TemplateView.as_view(template_name='core/suggestions_sent.html'), name="suggestions"), # noqa
    url(r'^suggerimenti/', SuggestionsFormView.as_view(), name="suggestions"), # noqa
    # agreements
    url(r'^convenzioni/', include('agreements.urls')),
    # smart_selects
    url(r'^chaining/', include('smart_selects.urls')),
    # captcha
    url(r'^captcha/', include('captcha.urls')),
    # agreements
    url(r'inserisci-convenzioni/inviata/', TemplateView.as_view(template_name='core/proposal_sent.html'), name="proposals"), # noqa
    url(r'^inserisci-convenzioni/', login_required(AgreementProposalView.as_view())),
    # old urls
    url(r'^r/', RewriteView.as_view(), name="rewrite"), # noqa
    url(r'^robots\.txt$', TemplateView.as_view(template_name='core/robots.txt', content_type='text/plain')), # noqa
    # newsfeeds
    url(r'^newsfeeds/', news_feeds),
    # blog
    url(r'^blog/', include('blog.urls')),
    # API
    url(r'^api/v1/', include(router.urls))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    ]
    urlpatterns += [
        url(r'^static/(?P<path>.*)$',
            'django.contrib.staticfiles.views.serve'),
    ]

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

convenzioni-cisl-uil/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.sites.shortcuts import get_current_site

from captcha.fields import CaptchaField

from agreements.models import Region, Province, City, Category


class SuggestionsForm(forms.Form):
    email = forms.EmailField(label='e-mail', required=True)
    message = forms.CharField(
        label='messaggio',
        required=True,
        widget=forms.Textarea)
    captcha = CaptchaField()


class ProposalForm(forms.Form):
    firstname = forms.CharField(label='nome', required=True)
    lastname = forms.CharField(label='cognome', required=True)
    phone = forms.CharField(label='telefono', required=True)
    head_office = forms.CharField(label='sede sindacale', required=True)
    referer = forms.CharField(
        label='nominativo del referente/titolare punto vendita',
        required=True,
        help_text='con cui si è stipulata la convenzione')
    begin_date = forms.CharField(label='data stipula convenzione',
                                 required=True)
    end_date = forms.CharField(label='data termine convenzione',
                               required=False)

    company_name = forms.CharField(label='nome azienda', required=True)
    company_address = forms.CharField(label='indirizzo', required=True)
    company_region = forms.ModelChoiceField(
        label='regione',
        required=False,
        queryset=Region.objects.all())
    company_region_other = forms.CharField(label='altra regione',
                                           required=False)
    company_province = forms.ModelChoiceField(
        label='provincia',
        empty_label='clicca qui per scegliere',
        required=False,
        queryset=Province.objects.all())
    company_province_other = forms.CharField(label='altra provincia',
                                             required=False)
    company_city = forms.ModelChoiceField(
        label='comune',
        empty_label='clicca qui per scegliere',
        required=False,
        queryset=City.objects.all())
    company_city_other = forms.CharField(label='altro comune',
                                         required=False)
    company_phone = forms.CharField(label='telefono', required=True)
    company_web = forms.CharField(label='sito web', required=False)
    company_email = forms.CharField(label='e-mail', required=False)
    company_category = forms.ModelChoiceField(
        label='categoria merceologica',
        empty_label='clicca qui per scegliere',
        required=False,
        queryset=Category.objects.filter(sites__in=[get_current_site(None), ]))
    # queryset=Category.objects.all())
    company_category_other = forms.CharField(label='nuova categoria',
                                             required=False)
    company_category_other2 = forms.CharField(label='altra categoria',
                                             required=False)
    company_description = forms.CharField(
        label='descrizione, percentuale sconto/agevolazione',
        required=True,
        widget=forms.Textarea)
    captcha = CaptchaField()
    site = forms.IntegerField(label='sito', required=False)

convenzioni-cisl-uil/core/views.py
import json
import feedparser
from dateutil import parser

from django.views.generic.edit import FormView
from django.views.generic import View
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import send_mail
from django.conf import settings
from django.http import Http404
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.sites.models import Site

from .forms import SuggestionsForm, ProposalForm
from agreements.models import Category, Region, Province, Proposal


class SuggestionsFormView(FormView):
    template_name = 'core/suggestions.html'
    form_class = SuggestionsForm
    success_url = '/suggerimenti/inviati/'

    def form_valid(self, form):

        email = form.cleaned_data['email']
        message = form.cleaned_data['message']

        if email and message:
            mail_subject = '%s - Suggerimenti da %s' % (self.request.site.name, email) # noqa
            mail_object = message
            send_mail(mail_subject, mail_object, settings.SITE['MAIL_NOREPLY'], (settings.SITE['MAIL_CONVENZIONI'], )) # noqa

        return super(SuggestionsFormView, self).form_valid(form)


class RewriteView(View):

    def get(self, request):
        if (request.GET.get('idcategoria', None)):
            category = get_object_or_404(Category, old_id=request.GET.get('idcategoria')) # noqa
            return redirect('agreements-list', category_slug=category.slug)
        if (request.GET.get('IDCATEGORIA', None)):
            category = get_object_or_404(Category, old_id=request.GET.get('IDCATEGORIA')) # noqa
            return redirect('agreements-list', category_slug=category.slug)
        raise Http404


class AgreementProposalView(FormView):
    template_name = 'core/proposal.html'
    form_class = ProposalForm
    success_url = '/inserisci-convenzioni/inviata/'

    def get_context_data(self, **kwargs):
        context = super(AgreementProposalView, self).get_context_data(**kwargs)
        current_site = get_current_site(None)
        context['site'] = current_site.id
        regions = {}
        provinces = {}
        for r in Region.objects.all():
            arr = []
            for p in r.provinces.all():
                arr.append(p.id)
            regions[r.id] = arr
        context['regions_dict'] = json.dumps(regions)
        for p in Province.objects.all():
            arr = []
            for c in p.cities.all():
                arr.append(c.id)
            provinces[p.id] = arr
        context['provinces_dict'] = json.dumps(provinces)
        return context

    def form_valid(self, form):
        firstname = form.cleaned_data['firstname']
        lastname = form.cleaned_data['lastname']
        phone = form.cleaned_data['phone']
        head_office = form.cleaned_data['head_office']
        referer = form.cleaned_data['referer']
        begin_date = form.cleaned_data['begin_date']
        end_date = form.cleaned_data['end_date']
        company_name = form.cleaned_data['company_name']
        company_address = form.cleaned_data['company_address']
        company_region = form.cleaned_data['company_region']
        company_region_other = form.cleaned_data['company_region_other']
        company_province = form.cleaned_data['company_province']
        company_province_other = form.cleaned_data['company_province_other']
        company_city = form.cleaned_data['company_city']
        company_city_other = form.cleaned_data['company_city_other']
        company_phone = form.cleaned_data['company_phone']
        company_web = form.cleaned_data['company_web']
        company_email = form.cleaned_data['company_email']
        company_category = form.cleaned_data['company_category']
        company_category_other = form.cleaned_data['company_category_other']
        company_category_other2 = form.cleaned_data['company_category_other2']
        company_description = form.cleaned_data['company_description']
        site = form.cleaned_data['site']

        proposal = Proposal(
            firstname=firstname,
            lastname=lastname,
            phone=phone,
            head_office=head_office,
            referer=referer,
            begin_date=begin_date,
            end_date=end_date,
            company_name=company_name,
            company_address=company_address,
            company_region=company_region,
            company_region_other=company_region_other,
            company_province=company_province,
            company_province_other=company_province_other,
            company_city=company_city,
            company_city_other=company_city_other,
            company_phone=company_phone,
            company_web=company_web,
            company_email=company_email,
            company_category=company_category,
            company_category_other=company_category_other,
            company_category_other2=company_category_other2,
            company_description=company_description,
            site=Site.objects.get(id=site),
        )
        proposal.save()

        current_site = get_current_site(None)

        send_mail(
            'Inserimento nuova convenzione',
            'Nuova proposta di convenzione inserita su %s.' % current_site.domain, # noqa
            settings.SITE['MAIL_NOREPLY'],
            ('direzione@rtpcomunicazione.it', )
        ) # noqa

        return super(AgreementProposalView, self).form_valid(form)


def news_feeds(request):
    current_site = get_current_site(request)
    url = settings.SITE['FEED_URL']
    feeds = feedparser.parse(url)
    fs = []
    try:
        for i in range(0, 6):
            feed = feeds['entries'][i]
            obj = {
                'feed': feed,
                'published': parser.parse(feed.published).strftime('%d %b %Y'),
                'link': feed.links[0]['href']
            }
            fs.append(obj)
    except:
        fs = []

    return render(
        request,
        'core/news_feeds_content.html',
        {
            'site': current_site,
            'feeds': feeds,
            'fs': fs,
            'list_url': settings.SITE['FEED_PAGE'],
            'union': settings.SITE['UNION']
        }
    )

convenzioni-cisl-uil/core/templates/core/news_feeds.html
{% load core_tags %}
<section class="feeds">
    <h1>Notizie dalla {{ union }}</h1>
    <div id="news-feeds">
        <i class="fa fa-spinner fa-spin fa-2x" style="margin: 20px 10px 20px 0"></i> Caricamento in corso
    </div>
    <script>
        (function ($) {
            $.get('/newsfeeds/', function (res) {
                $('#news-feeds').html(res)
            })
        })(jQuery)
    </script>
</section>

convenzioni-cisl-uil/core/templates/core/news_feeds_content.html
{% if fs|length %}
    <div class="loading-bar">
        <div class="loading-knot"></div>
    </div>
{% endif %}
<div class="feeds-container">
{% if fs|length %}
    {% for f in fs %}
        <article class="feeds-slide{% if forloop.counter == 1%} active{% endif %}">
            <h1>{{ f.published }} - <a href="{{ f.link }}" target="_blank">{{ f.feed.title }}</a></h1>
            <p>{{ f.feed.summary | striptags | safe | truncatewords:50 }}</p>
        </article>
    {% endfor %}
{% else %}
    <p>Servizio momentaneamente non disponibile</p>
{% endif %}
</div>
<p class="text-right">
    <a href="{{ list_url }}" class="btn btn-custom" target="_blank">elenco completo</a>
</p>
{% if fs|length %}
<script type="text/javascript">
    (function ($, undefined) {
        var slides = $('.feeds-slide');
        var animate = function () {
            $( ".loading-knot" ).animate({
                width: "100%",
                queue: false
            }, 9000);
        }
        animate();
        setInterval(function () {
            $( ".loading-knot" ).animate({
                width: 0,
                queue: false
            }, 0);
            animate();
            var active = $('.feeds-slide.active');
            $(active).removeClass('active');
            if ($(active).next('.feeds-slide').length) {
                $(active).next('.feeds-slide').addClass('active');
            }
            else {
                $(slides[0]).addClass('active');
            }
        }, 9000)
    })(jQuery, undefined)
</script>
{% endif %}

convenzioni-cisl-uil/core/templates/core/newsletter_registration_form_cisl.html
<section class="newsletter">
    <h1>Iscriviti alla nostra newsletter</h1>
    <p>Per ricevere aggiornamenti su nuove convenzioni, promozioni e offerte riservate agli iscritti CISL e ai loro famigliari.</p>
    <p>
        <a title="Iscriviti tramite Facebook" href="http://mc1l3.mailrouter.it/user/register_facebook">
            <span class="btn btn-primary" style="background: #3B5998"><i class="fa fa-facebook"></i> tramite facebook</span>
        </a>
    </p>
    <form action="https://mc1l3.mailrouter.it/user/register"  accept-charset="UTF-8" method="post">
        <div class="row">
            <div class="col-lg-6">
                <p>
                <input type="text" maxlength="64" name="mail" placeholder="e-mail" value="" class="form-control form-text required" required/>
                </p>
                <p>
                <input placeholder="categoria CISL" type="text" maxlength="255" name="profile_categoria_cisl" value="" class="form-control form-text" />
                </p>
                <p>
                    <input placeholder="cap" type="text" maxlength="255" name="profile_cap_di_residenza" value="" class="form-text form-control" />
                </p>
            </div>
            <div class="col-lg-6">
                <p>
                <input placeholder="nome" type="text" maxlength="255" name="profile_name" value="" class="form-control form-text" />
                </p>
                <p>
                <input placeholder="cognome" type="text" maxlength="255" name="profile_surname" value="" class="form-control form-text" />
                </p>
            </div>
        </div>
        <p>
            <input type="checkbox" name="privacy" value="1"   class="form-checkbox has-sibling-label" /><label style="display: inline; font-size: 0.8em;" class="option" for=""> Acconsento al trattamento dei miei dati personali (<a href="/cookie-policy/" target="_blank">leggi qui</a> la nostra politica sulla privacy e come trattiamo i tuoi dati)</label>
        </p>
        <p>
            <input type="submit" name="submit" value="Iscriviti"  class="btn btn-custom form-submit" />
            <input type="hidden" name="form_id" value="user_register"  />
        </p>
        <script type="text/javascript">
            var openPrivacyModal = function () {
                var modal = new core.Modal({
                    title: 'Trattamento dati personali',
                    content: "Ai sensi del d.lgs. 196/2003, La informiamo che: <br />a) titolare del trattamento è UFFICIO CONVENZIONI CISL - RTP COMUNICAZIONE, 10143 TORINO, via Locana 13/l.,<br />b) responsabile del trattamento è Elio Dogliotti, 10143 Torino, via Locana 13/L<br />c) i Suoi dati saranno trattati (anche elettronicamente) soltanto dagli incaricati autorizzati, esclusivamente per dare corso all'invio della newsletter e per l'invio (anche via email) di informazioni relative alle iniziative del Titolare; <br />d) la comunicazione dei dati è facoltativa, ma in mancanza non potremo evadere la Sua richiesta; <br />e) ricorrendone gli estremi, può rivolgersi all'indicato responsabile per conoscere i Suoi dati, verificare le modalità del trattamento, ottenere che i dati siano integrati, modificati, cancellati, ovvero per opporsi al trattamento degli stessi e all'invio di materiale. Preso atto di quanto precede, acconsento al trattamento dei miei dati."
                });
                modal.open();
            }
        </script>
    </form>
</section>

convenzioni-cisl-uil/core/templates/core/proposal.html
{% extends 'page.html' %}
{% load widget_tweaks %}
{% load flatpages %}

{% block title %}
Inserisci convenzione | {{ block.super }}
{% endblock %}

{% block section2_content %}
    <section>
        <h1>Inserisci una convenzione</h1>
        {% get_flatpages '/inserisci-convenzioni-prologo/' as pages %}
        {% for page in pages %}
            {{ page.content|safe }}
        {% endfor %}
        <p class="alert alert-info">I campi contrassegnati con l'asterisco sono obbligatori.</p>

        {% if form.errors %}
            <p class="alert alert-danger">Correggi gli errori nei campi evidenziati dalla cornice rossa.</p>
        {% endif %}
        {% if form.non_field_errors %}
            <ul class="form-error">
            {% for error in form.non_field_errors %}
                <li class="alert alert-danger"><i class="fa fa-exclamation-triangle"></i> {{ error|escape }}</li>
            {% endfor %}
            </ul>
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group" style="display: none">
                <input type="hidden" id='id_site' name="site" value="{{ site }}" />
            </div>
            <div class="form-group">
                <label class="required">Nome</label>
                {{ form.firstname|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label class="required">Cognome</label>
                {{ form.lastname|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label class="required">Telefono di contatto</label>
                {{ form.phone|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label class="required">Sede sindacale</label>
                {{ form.head_office|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label class="required">Nominativo referente/punto vendita della convenzione</label>
                {{ form.referer|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label class="required">Data stipula convenzione</label>
                {{ form.begin_date|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label>Eventuale data di termine convenzione</label>
                {{ form.end_date|attr:"class:form-control" }}
            </div>

            <h2>Dati azienda</h2>

            <div class="form-group">
                <label class="required">Nome</label>
                {{ form.company_name|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label class="required">Indirizzo</label>
                {{ form.company_address|attr:"class:form-control"|attr:"required" }}
            </div>
            <div class="form-group">
                <label class="required">Regione</label>
                {{ form.company_region|attr:"class:form-control c-select"|attr:"required" }}
            </div>
            <div class="form-group">
                <label>Provincia</label>
                {{ form.company_province|attr:"class:form-control c-select" }}
            </div>
            <div class="form-group">
                <label class="required">Nuova provincia</label>
                {{ form.company_province_other|attr:"class:form-control"|attr:"required" }}
                <p class="text-muted">Inserire la provincia qui se non presente nel menu a tendina</p>
            </div>
            <div class="form-group">
                <label>Comune</label>
                {{ form.company_city|attr:"class:form-control c-select" }}
            </div>
            <div class="form-group">
                <label class="required">Nuovo comune</label>
                {{ form.company_city_other|attr:"class:form-control"|attr:"required" }}
                <p class="text-muted">Inserire il comune qui se non presente nel menu a tendina</p>
            </div>
            <div class="form-group">
                <label class="required">Telefono</label>
                {{ form.company_phone|attr:"class:form-control"|attr:"required" }}
                <p class="text-muted">Inserire un numero fisso e/o mobile aziendale</p>
            </div>
            <div class="form-group">
                <label class="">Sito web (se disponibile)</label>
                {{ form.company_web|attr:"class:form-control" }}
            </div>
            <div class="form-group">
                <label class="">E-mail</label>
                {{ form.company_email|attr:"class:form-control" }}
            </div>
            <div class="form-group">
                <label>Categoria merceologica</label>
                {{ form.company_category|attr:"class:form-control c-select" }}
            </div>
            <div class="form-group">
                <label class="required">Nuova categoria</label>
                {{ form.company_category_other|attr:"class:form-control"|attr:"required" }}
                <p class="text-muted">Inserire la categoria qui se non presente nel menu a tendina</p>
            </div>
            <div class="form-group">
                <label>Categoria aggiuntiva (opzionale)</label>
                {{ form.company_category_other2|attr:"class:form-control" }}
            </div>
            <div class="form-group">
                <label class="required">Descrizione punto vendita, percentuale sconto/agevolazione (max 400 caratteri)</label>
                {{ form.company_description|attr:"class:form-control"|attr:"required"|attr:"maxlength:400" }}
            </div>
            <div class="form-group">
                <label class="required" for="id_beds">Inserisci il codice nell'immagine</label>
                {% if form.captcha.errors %}
                    <ul class="form-error">
                    {% for error in form.captcha.errors %}
                        <li class="alert alert-danger"><i class="fa fa-exclamation-triangle"></i> {{ error|escape }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
                {{ form.captcha|attr:"class:form-control"|attr:"required" }}
            </div>
            <p>
                <input type="submit" class="btn btn-custom" value="invia" name="submit_agreement" />
            </p>
        </form>
        {% get_flatpages '/inserisci-convenzioni-epilogo/' as pages %}
        {% for page in pages %}
            {{ page.content|safe }}
        {% endfor %}
        <script type="text/javascript">
            (function () {
                var dft = {% if SITE.SITE == 'UILMARCHE' %}13{% else %}1{% endif %};

                // default region Piemonte
                if (!$('#id_company_region').val()) {
                    $('#id_company_region').val(dft)
                }

                {% autoescape off %}
                var regions_dict = {{ regions_dict}};
                var provinces_dict = {{ provinces_dict }};
                {% endautoescape %}

                var proposalForm = function () {
                    var field = $(this).attr('id').substring(11);
                    var field_other = $('#id_company_' + field + '_other')
                    var label_other = field_other.prev('label')
                    if (field !== 'region') {
                        if (!$(this).val()) {
                            $(this).prev('label').removeClass('required');
                            $(this).removeAttr('required');
                            label_other.attr('required', 'required');
                            if (!label_other.hasClass('required')) {
                                label_other.addClass('required')
                            }
                        } else {
                            $(this).attr('required', 'required');
                            if (!$(this).prev('label').hasClass('required')) {
                                $(this).prev('label').addClass('required');
                            }
                            label_other.removeClass('required');
                            field_other.removeAttr('required')
                        }
                    }

                    var val = $(this).val()
                    if (field == 'region') {
                        if (!val) {
                            $('#id_company_province option').each(function (index, opt) {
                                if($(opt).val()) {
                                    $(opt).css('display', 'none')
                                }
                            })
                        } else {
                            $('#id_company_province option').each(function (index, opt) {
                                if ($.inArray(parseInt($(opt).attr('value')), regions_dict[val]) != -1 || $(opt).attr('value') == '') {
                                    $(opt).css('display', '')
                                } else {
                                    $(opt).css('display', 'none')
                                }
                            })
                        }
                        if ($.inArray(parseInt($('#id_company_province').val()), regions_dict[val]) == -1) {
                            $('#id_company_province').val('');
                        }
                        $('#id_company_province').trigger('change');
                    }
                    if (field == 'province') {
                        if (!val) {
                            $('#id_company_city option').each(function (index, opt) {
                                if($(opt).val()) {
                                    $(opt).css('display', 'none')
                                }
                            })
                        } else {
                            $('#id_company_city option').each(function (index, opt) {
                                if ($.inArray(parseInt($(opt).attr('value')), provinces_dict[val]) != -1 || $(opt).attr('value') == '') {
                                    $(opt).css('display', '')
                                } else {
                                    $(opt).css('display', 'none')
                                }
                            })
                        }
                        if ($.inArray($('#id_company_city').val(), provinces_dict[val]) == -1) {
                            $('#id_company_city').val('');
                        }
                    }
                }

                $('#id_company_region, #id_company_province, #id_company_city, #id_company_category').on('change', proposalForm);
                $('#id_company_region, #id_company_province, #id_company_city, #id_company_category').each(function (index, el) {
                    proposalForm.call(el);
                });

            })()
        </script>
    </section>
{% endblock %}

convenzioni-cisl-uil/core/templates/core/proposal_sent.html
{% extends 'page.html' %}
{% load flatpages %}

{% block title %}
Inserisci convenzione | {{ block.super }}
{% endblock %}

{% block section2_content %}
    <section>
        <h1>Inserimento convenzione</h1>
        {% get_flatpages '/inserisci-convenzioni-inviata/' as pages %}
        {% for page in pages %}
            {{ page.content|safe }}
        {% endfor %}
        <p>
            <a href="/inserisci-convenzioni/" class="btn btn-primary">Inserisci una nuova convenzione</a>
            <a href="/" class="btn btn-primary">Vai in home page</a>
        </p>
    </section>
{% endblock %}

convenzioni-cisl-uil/core/templates/core/suggestions.html
{% extends 'page.html' %}

{% block title %}
Suggerimenti | {{ block.super }}
{% endblock %}

{% block section2_content %}
    <section>
        <h1>Suggerimenti</h1>
        <p>Compila il form sottostante per inviarci suggerimenti riguardo nuove convenzioni:</p>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input required type="email" class="text form-control" value="" name="email" id="id_email" placeholder="e-mail" />
            </div>
            <div class="form-group">
                <textarea style="min-height: 140px" required name="message" class="form-control" id="id_message" placeholder="Scrivi qui i tuoi suggerimenti (es. il nome di un nuovo negozio, una categoria mancante, una zona in cui vorresti ci fossero esercizi convenzionati ecc. Se aggiungi anche il tuo numero di telefono, ti chiameremo per farci spiegare meglio il tuo suggerimento o per rispondere subito ad una tua richiesta)"></textarea>
            </div>
            <div class="form-group">
                <label>Codice di controllo: </label><br />
                {% if form.captcha.errors %}
                <div class="alert alert-danger">
                    {{ form.captcha.errors }}
                </div>
                {% endif %}
                {{ form.captcha }}
            </div>
            <p>
                <input type="submit" class="btn btn-custom" value="invia" name="submit_suggestions" />
            </p>
        </form>
    </section>
{% endblock %}

convenzioni-cisl-uil/core/templates/core/suggestions_sent.html
{% extends 'page.html' %}

{% block title %}
Suggerimenti | {{ block.super }}
{% endblock %}

{% block section2_content %}
    <section>
        <h1>Suggerimenti</h1>
        <p class="alert alert-info">Grazie! La tua segnalazione è stata inviata correttamente.</p>
    </section>
{% endblock %}