convenzioni-cisl-uil/ads/urls.py
from django.conf.urls import url
from .views import TraceUrl

urlpatterns = [
    url(r'^apri/(?P<pk>\d+)$', TraceUrl.as_view(), name='ads-trace-url'),
]

convenzioni-cisl-uil/news/urls.py
from django.conf.urls import patterns,url
from .views import NewsDetailView, NewsListView, NewsCreateView, NewsDeleteView

urlpatterns = patterns('news.views',
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', NewsDetailView.as_view(), name='news-detail'),
    url(r'^archivio/$', NewsListView.as_view(), name='news-archive'),
    url(r'^crea/$', NewsCreateView.as_view(), name='news-create'),
    url(r'^elimina/(?P<pk>\d+)$', NewsDeleteView.as_view(), name='news-delete'),
)

convenzioni-cisl-uil/news/models.py
# -*- coding: utf-8 -*-
import os

from django.db import models
from django.contrib.sites.models import Site
from django.contrib.sites.shortcuts import get_current_site
from django.utils import timezone

from ckeditor_uploader.fields import RichTextUploadingField
from colorful.fields import RGBColorField

from .managers import NewsManager


class Label(models.Model):
    name = models.CharField(verbose_name='nome', max_length=64)
    icon = models.CharField(
        verbose_name='icona',
        max_length=32,
        help_text='Utilizzare classi FontAwesome es. fa-exclamation-triangle (http://fortawesome.github.io/Font-Awesome/icons/)' # noqa
    )
    color = RGBColorField(verbose_name='colore')

    class Meta:
        verbose_name = 'etichetta'
        verbose_name_plural = 'etichette'

    def __unicode__(self):
        return '%s' % self.name


class News(models.Model):
    """ News model
    """
    insertion_date = models.DateTimeField('inserimento', auto_now_add=True)
    last_edit_date = models.DateTimeField('ultima modifica', auto_now=True)
    date = models.DateField('data', null=True, blank=True)
    date_from = models.DateField('da', default=timezone.now)
    date_to = models.DateField('a', blank=True, null=True)
    evidence = models.BooleanField('In evidenza', default=False)
    title = models.CharField(verbose_name='titolo', max_length=255)
    slug = models.SlugField(max_length=255)
    image = models.ImageField('immagine', upload_to='news/img')
    text = RichTextUploadingField(verbose_name='testo')
    label = models.ForeignKey(Label, verbose_name='etichetta', null=True,
                              blank=True)
    featured = models.BooleanField('featured')
    show_date = models.BooleanField('mostra data')
    published = models.BooleanField('pubblicata')
    sites = models.ManyToManyField(Site, verbose_name='siti')

    objects = NewsManager()

    class Meta:
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def __unicode__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('news-detail',
                       args=[
                           str(self.insertion_date.year),
                           self.insertion_date.strftime("%m"),
                           self.insertion_date.strftime("%d"), self.slug])

    def get_full_absolute_url(self):
        current_site = get_current_site(None)
        return ''.join([
            'http://',
            current_site.domain,
            self.get_absolute_url()
        ])

    def get_full_img_url(self):
        current_site = get_current_site(None)
        if self.image:
            return ''.join([
                'http://',
                current_site.domain,
                self.image.url
            ])
        return ''


class Attachment(models.Model):
    """ Attachment model
    """
    news = models.ForeignKey(News, verbose_name='news',
                             related_name='attachments')
    name = models.CharField(verbose_name='nome', max_length=128)
    file = models.FileField(upload_to='news/attachment')

    @property
    def extension(self):
        return os.path.splitext(self.file.url)[1][1:]

    @property
    def size(self):
        kb = self.file.size/1000
        if(kb):
            return '%s %s' % (str(kb), 'kB')
        else:
            return '%s %s' % (self.file.size, 'B')

    class Meta:
        verbose_name = 'allegato'
        verbose_name_plural = 'allegati'

    def __unicode__(self):
        return '%s' % self.name

convenzioni-cisl-uil/news/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from .models import News, Attachment


class NewsForm(ModelForm):
    class Meta:
        model = News
        fields = ['date', 'title', 'text', 'label', 'featured', 'published',]

class AttachmentForm(ModelForm):
    class Meta:
        model = Attachment
        fields = '__all__'

AttachmentFormSet = inlineformset_factory(News, Attachment, form=AttachmentForm, extra=3)

convenzioni-cisl-uil/news/views.py
import logging
import datetime

from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, DeleteView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.db import transaction
from django.template.defaultfilters import slugify
from django.http import Http404

from .models import News
from .forms import NewsForm, AttachmentFormSet

logger = logging.getLogger(__name__)


class NewsDetailView(DetailView):
    """ Single news detail view
    """
    model = News

    def get_queryset(self):
        return News.objects.filter(sites__in=[self.request.site]).published()

    def get_object(self):
        news = News.objects.published(
            slug=self.kwargs['slug'],
            sites__in=[self.request.site]
        )
        #@FIXME needed because probably due to mysql installation month and day lookups do not work!
        if news.count:
            for n in news:
                if n.insertion_date.year == int(self.kwargs['year']) and n.insertion_date.month == int(self.kwargs['month']) and n.insertion_date.day == int(self.kwargs['day']):
                    return n
        else:
            raise Http404

        raise Http404

class NewsListView(ListView):
    """ News archive view
    """
    model = News
    paginate_by = 10

    def get_queryset(self):
        return News.objects.published(sites__in=[self.request.site]).order_by('-insertion_date')  # noqa

class NewsCreateView(CreateView):
    model = News
    form_class = NewsForm

    @method_decorator(permission_required('news.can_add'))
    def dispatch(self, request, *args, **kwargs):
        return super(NewsCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        data = super(NewsCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['formset'] = AttachmentFormSet(self.request.POST, self.request.FILES)
        else:
            data['formset'] = AttachmentFormSet()

        return data

    def form_invalid(self, form):
        logger.info('NewsCreateView: form invalid')
        return super(NewsCreateView, self).form_invalid(form)

    @transaction.atomic
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        form.instance.slug = slugify(form.instance.title)
        form.instance.text = '<p>' + form.instance.text.replace('\n','<br />\n') + '</p>'
        self.object = form.save()
        logger.info('NewsCreateView: new object id: %s' % self.object.id)
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return render(self.request, 'news/news_create_success.html', {'news': self.object})

class NewsDeleteView(DeleteView):
    model = News
    success_url = '/'

    @method_decorator(permission_required('news.can_delete'))
    def dispatch(self, request, *args, **kwargs):
        return super(NewsDeleteView, self).dispatch(request, *args, **kwargs)

convenzioni-cisl-uil/news/templates/news/evidence.html
{% load static %}
{% load core_tags %}
{% if news.count %}
    <section class="evidence-showcase">
        <h1>{{ title }}</h1>
        {% for n in news %}
          <article class="{% if forloop.first %}active{% endif %}" data-news="{{ forloop.counter }}" style="background-image: url('{{ n.image.url }}')">
            <h1 class="text-center">
                {% if n.label %}
                    <i class="fa fa-2x {{ n.label.icon }}" style="color: {{ n.label.color }}"></i>
                {% endif %}
                {% if n.show_date %}<span>{{ n.date|date:'d/m/Y' }}</span> - {% endif %}<a href="{{ n.get_absolute_url }}">{{ n.title }}</a>
            </h1>
        </article>
        {% endfor %}
        <div class="ctrls">
            {% for n in news %}
                <span class="dot {% if forloop.first %}active{% endif %}" data-index="{{ forloop.counter }}"></span>
            {% endfor %}
        </div>
        <p class="readallp">
            <a title="archivio completo" class="btn btn-custom" data-toggle="tooltip" href="{% url 'news-archive' %}">tutte le notizie</a>
        </p>
    </section>
    <script>
        (function($, undefined) {
            var dots = $('.evidence-showcase .dot');
            var go = function (el) {
                var index = $(el).attr('data-index');
                $('.evidence-showcase article').removeClass('active');
                $('.evidence-showcase article[data-news=' + index + ']').addClass('active');
                $('.evidence-showcase .dot').removeClass('active');
                $(el).addClass('active');
            }
            dots.on('click', function(e) {
                go($(this));
            });

            var currentClickIndex = 1;
            setInterval(function () {
                if (currentClickIndex >= dots.length) {
                    currentClickIndex = 0;
                }
                go($(dots[currentClickIndex]));
                currentClickIndex++;
            }, 12000)
         })(jQuery);
    </script>
{% endif %}

convenzioni-cisl-uil/news/templates/news/news_confirm_delete.html
{% extends 'page.html' %}
{% load news_tags %}

{% block title %}
{{ object.title }} | {{ block.super }}
{% endblock %}

{% block main_content %}
    <section>
        <h1>Eliminazione notizia</h1>
        <p>
            Conferma l'eliminazione della notizia:<br />
            <strong>{{ object.title }}</strong>
        </p>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="elimina" />
            <input type="button" class="btn btn-defaul" value="annulla" onclick="history.go(-1)" />
        </form>
    </section>
{% endblock %}

{% block sidebar %}
    {% news_showcase %}
{% endblock sidebar %}

convenzioni-cisl-uil/news/templates/news/news_create_success.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Chiudi</span>
            </button>
            <h4 class="modal-title">Inserimento notizia</h4>
        </div>
        <div class="modal-body">
            <p class="alert alert-info">La notizia "{{ news.title }}" è stata correttamente inserita</p>
        </div><!-- /.modal-body -->
     </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
<script>
    setTimeout(function() {
        $('#modal').modal('hide');
    }, 2000);
</script>

convenzioni-cisl-uil/news/templates/news/news_detail.html
{% extends 'page.html' %}
{% load news_tags %}

{% block title %}
{{ object.title }} | {{ block.super }}
{% endblock %}

{% block meta_title %}{{ object.title|escape }}{% endblock %}
{% block meta_description %}{% autoescape on %}{{ object.text|striptags|slice:":152" }}...{% endautoescape %}{% endblock %}
{% block meta_og_title %}{{ object.title|escape }}{% endblock %}
{% block meta_og_description %}{% autoescape on %}{{ object.text|striptags|slice:":294" }}...{% endautoescape %}{% endblock %}
{% block meta_og_url %}{{ object.get_full_absolute_url|urlencode }}{% endblock %}
{% block meta_tw_title %}{{ object.title|escape }}{% endblock %}
{% block meta_tw_description %}{% autoescape on %}{{ object.text|striptags|slice:":197" }}...{% endautoescape %}{% endblock %}
{% block meta_tw_url %}{{ object.get_full_absolute_url|urlencode }}{% endblock %}
{% block meta_extra %}
    {% if object.image %}
        <meta name="og:image" content="{{ object.get_full_img_url }}" />
        <meta name="twitter:image" content="{{ object.get_full_img_url }}" />
    {% endif %}
{% endblock %}

{% block section2_content %}
    <section>
        <h1>{{ object.title }}</h1>
        {% if object.date and object.show_date %}
            <p><i class="fa fa-calendar"></i> {{ object.date }}</p>
        {% endif %}
        <div class="share clearfix">
            <!-- AddToAny BEGIN -->
            <div class="a2a_kit a2a_kit_size_32 a2a_default_style" style="float: right">
                <a class="a2a_dd" href="https://www.addtoany.com/share?linkurl={{ object.get_full_absolute_url }}&amp;linkname={{ object.title|urlencode }}"></a>
                <a class="a2a_button_facebook"></a>
                <a class="a2a_button_twitter"></a>
                <!-- <a class="a2a_button_google_plus"></a> -->
                <a class="a2a_button_whatsapp"></a>
            </div>
            <script>
            var a2a_config = a2a_config || {};
            a2a_config.linkname = "{{ object.title | escape }}";
            a2a_config.linkurl = "{{ object.get_full_absolute_url }}";
            a2a_config.locale = "it";
            </script>
            <script async src="https://static.addtoany.com/menu/page.js" data-cookierulez="functionality" type="text/plain"></script>
            <!-- AddToAny END -->
            <a href="{% url 'news-archive' %}" class="btn btn-custom" style="float: left !important;">tutte le notizie</a>
        </div>
        {% if object.image %}
        <p><img src="{{ object.image.url }}" class="img-responsive" /></p>
        {% endif %}
        {% if object.label %}
            <i class="pull-right fa fa-2x {{ object.label.icon }}" style="color: {{ object.label.color }}"></i>
        {% endif %}
        {{ object.text|safe }}
        {% if object.attachments.count %}
            <h2>Documenti</h2>
            <ul class="padding-l10">
            {% for attachment in object.attachments.all %} 
                <li class="ext ext-{{ attachment.extension }}"><a href="{{ attachment.file.url }}">{{ attachment.name }}</a> ({{ attachment.size }})</li>
            {% endfor %}
            </ul>
        {% endif %}
    </section>
{% endblock %}

convenzioni-cisl-uil/news/templates/news/news_form.html
{% load i18n widget_tweaks %}
<div class="modal-dialog modal-lg" role="document">
    <form action="{% url 'news-create' %}" method="post" class="form" id="news-create" enctype="multipart/form-data">{% csrf_token %}
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Chiudi</span>
            </button>
            <h2 class="modal-title">Nuova notizia</h2>
        </div>
        <div class="modal-body">
            {{ form.non_field_errors }}
            {% for field in form.visible_fields %}
                {% if field.name != 'slug' %}
                <fieldset class="form-group">
                    <label>
                        {% if field.field.required %}*{% else %}{% endif %}
                        {{ field.label_tag }}
                    </label>
                    {{ field.errors }}
                    {% if field.name == 'text' %}
                        <textarea name="text" id="id_text" class="form-control" required>{{ field.value|default_if_none:"" }}</textarea>
                    {% elif field.name == 'featured' or field.name == 'published' %}
                        {{ field|attr:"class:checkbox-inline" }}
                    {% else %}
                        {% if field.field.required %}
                            {{ field|attr:"class:form-control"|attr:"required:required" }}
                        {% else %}
                            {{ field|attr:"class:form-control" }}
                        {% endif %}
                    {% endif %}
                </fieldset>
                {% endif %}
            {% endfor %}
            <h3>Allegati</h3>
            {{ formset.management_form }}
            {% for form in formset %}
                {% if forloop.counter != 1 %}<hr />{% endif %}
                {% for field in form.visible_fields %}
                    <fieldset class="form-group">
                        {% if field.name == 'file' %}
                            <label>
                                {{ field.label_tag }}
                                {{ field.required }}
                            </label>
                            {{ field.errors }}
                            {{ field|attr:"class:form-control-file" }}
                        {% elif field.name == 'name' %}
                            <label>
                                {{ field.label_tag }}
                                {{ field.required }}
                            </label>
                            {{ field.errors }}
                            {{ field|attr:"class:form-control" }}
                        {% else %}
                        {% endif %}
                    </fieldset>
                {% endfor %}
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="button" id="save" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
            <input type="submit" class="btn btn-primary" value="Salva" />
        </div>
    </div><!-- /.modal-content -->
    </form>
</div><!-- /.modal-dialog -->
<script>
    $('#id_date').datepicker({
        //dateFormat: "dd/mm/yy"
    });
    var form_options = { target: '#modal', success: function(response) {
    } };
    $('#news-create').ajaxForm(form_options);
</script>

convenzioni-cisl-uil/news/templates/news/news_list.html
{% extends 'page.html' %}
{% load bootstrap_pagination %}

{% block title %}
Archivio notizie | {{ block.super }}
{% endblock %}

{% block section2_content %}
    <section>
        <h1>Archivio Notizie</h1>
        <table class="table table-bordered table-striped">
            <tr>
                <th>Tipo</th>
                <th>Notizia</th>
            </tr>
            {% for n in object_list %}
            <tr>
                <td>{% if n.label %}<i class="fa {{ n.label.icon }}" style="color: {{ n.label.color }}"></i>{% endif %}</td>
                <td><a href="{{ n.get_absolute_url }}">{{ n.title }}</a></td>
            </tr>
            {% endfor %}
        </table>
       {% comment %}FIXME add page numbers{% endcomment %}
        {% if is_paginated %}
            {% bootstrap_paginate page_obj range=10 %}
        {% endif %}
    </section>
{% endblock %}

convenzioni-cisl-uil/news/templates/news/showcase.html
{% load static %}
{% load core_tags %}
{% if news.count %}
    <section class="{{ class }}-showcase" style="margin-bottom: 50px;">
        <h1>{{ title }}</h1>
        {% for n in news %}
        <article class="{% if forloop.first %}active{% endif %}" data-news="{{ forloop.counter }}">
            <h1>
                {% if n.label %}
                    <i class="fa fa-2x {{ n.label.icon }}" style="color: {{ n.label.color }}"></i>
                {% endif %}
                {% if n.show_date %}<span>{{ n.date|date:'d/m/Y' }}</span> - {% endif %}<a href="{{ n.get_absolute_url }}">{{ n.title }}</a>
            </h1>
            <div class="row">
                <div class="col-sm-4">
                    {% if n.image %}
                    <p>
                        <img class="img-responsive" src="{{ n.image.url }}" />
                    </p>
                    {% endif %}
                </div>
                <div class="col-sm-8 {{ class }}-showcase-text">
                    {{ n.text|strip_img|safe|truncatewords_html:40 }}
                    <strong class="readall"><a href="{{ n.get_absolute_url }}">continua</a></strong>
                </div>
            </div>
        </article>
        {% endfor %}
        <div class="ctrls">
            {% for n in news %}
                <span class="dot {% if forloop.first %}active{% endif %}" data-index="{{ forloop.counter }}"></span>
            {% endfor %}
        </div>
        <p class="text-right" style="position: absolute; bottom: -45px; right: 10px; z-index: 100;">
            <a title="archivio completo" class="btn btn-custom" data-toggle="tooltip" href="{% url 'news-archive' %}">tutte le notizie</a>
        </p>
    </section>
    <script>
        (function($, undefined) {
            var dots = $('.{{ class }}-showcase .dot');
            var go = function (el) {
                var index = $(el).attr('data-index');
                $('.{{ class }}-showcase article').removeClass('active');
                $('.{{ class }}-showcase article[data-news=' + index + ']').addClass('active');
                $('.{{ class }}-showcase .dot').removeClass('active');
                $(el).addClass('active');
            }
            dots.on('click', function(e) {
                go($(this));
            });

            var setHeight = function (init) {
                var height = 0;
                var articles = $('.{{ class }}-showcase article');
                var loaded = 0;
                articles.each(function (idx, article) {
                    if (init) {
                        $(article).find('img').on('load', function () {
                            height = Math.max(height, $(article).outerHeight());
                            loaded++;
                            if (loaded === articles.length) {
                                articles.css('height', height);
                            }
                        })
                    } else {
                        $(article).css('height', 'auto');
                        height = Math.max(height, $(article).outerHeight());
                    }
                });
                if (!init) {
                    articles.css('height', height);
                }
            }

            setHeight(true);
            $(window).on('resize', function () { setHeight() });

            var currentClickIndex = 1;
            setInterval(function () {
                if (currentClickIndex >= dots.length) {
                    currentClickIndex = 0;
                }
                go($(dots[currentClickIndex]));
                currentClickIndex++;
            }, 12000)
         })(jQuery);
    </script>
{% endif %}